
export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST'
export const RECEIVED_ALL_DATA = 'RECEIVED_ALL_DATA'
export const FLIP_BOOL = 'FLIP_BOOL'
export const REMOVE_STOCK_FROM_WATCHLIST = 'REMOVE_STOCK_FROM_WATCHLIST'